service: liszt
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    LISZT_BUILDINGS_TABLE: liszt-buildings
    LISZT_UNITS_TABLE: liszt-units
    LISZT_UNITS_GSI: liszt-residents-testing
    LISZT_RESIDENTS_TABLE: liszt-residents
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:635281304921:liszt-buildings"
        - "arn:aws:dynamodb:us-west-2:635281304921:liszt-units"
        - "arn:aws:dynamodb:us-west-2:635281304921:table/liszt-units-testing/index/building_unit_gsi"
        - "arn:aws:dynamodb:us-west-2:635281304921:liszt-residents"
functions:
  buildingHandler:
    handler: handler.buildings
    events:
      - http:
          path: buildings/by_id
          method: get
          cors: true
      - http:
          path: buildings/register
          method: post
          cors: true
      - http:
          path: buildings/deregister
          method: post
          cors: true
      - http:
          path: buildings/units
          method: get
          cors: true
  unitHandler:
    handler: handler.units
    events:
      - http:
          path: buildings/units/register
          method: post
          cors: true
      - http:
          path: buildings/units/deregister
          method: post
          cors: true
      - http:
          path: buildings/units/residents
          method: get
          cors: true
  residentHandler:
    handler: handler.residents
    events:
      - http:
          path: residents/by_id
          method: get
          cors: true
      - http:
          path: residents/register
          method: post
          cors: true
      - http:
          path: residents/deregister
          method: post
          cors: true
      - http:
          path: residents/move_in
          method: post
          cors: true
      - http:
          path: residents/move_out
          method: post
          cors: true
